apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
  labels:
    app: todo-frontend
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: todo-frontend
